version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # env_file: .env
    depends_on:
      - redis
      - db
      - hub
    command: python manage.py runserver 0.0.0.0:8000

  redis:
    image: redis:latest
  
  celeryworker:
    <<: *django
    ports: []
    command: celery -A synchro worker -l INFO

  celerybeat:
    <<: *django
    ports: []
    command: celery -A synchro beat -l INFO --pidfile= --scheduler django_celery_beat.schedulers:DatabaseScheduler

  db:
    image: postgres

  hub:
    image: selenium/hub:3.141.59
    ports:
      - 4444:4444
    
  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub