version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      # - ./static:/static
    ports:
      - "8080:8080"
    # env_file: .env
    depends_on:
      - redis
      - db
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8080 djsync.wsgi"
  
  nginx:
    image: "nginx"
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - django

  redis:
    image: redis:latest
  
  celeryworker:
    <<: *django
    ports: []
    command: celery -A synchro worker -l INFO

  celerybeat:
    <<: *django
    ports: []
    command: celery -A synchro beat -l INFO --pidfile= --scheduler django_celery_beat.schedulers:DatabaseScheduler

  db:
    image: postgres