# Generated by Django 2.2.7 on 2019-11-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('available', models.FloatField()),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
