# Generated by Django 2.2.7 on 2019-11-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchro', '0003_auto_20191128_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('access_token', models.CharField(max_length=200)),
                ('expires_in', models.DateTimeField()),
            ],
        ),
    ]
