# Generated by Django 2.2.7 on 2019-11-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchro', '0004_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='access_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='expires_in',
            field=models.DateTimeField(null=True),
        ),
    ]
