# Generated by Django 2.2 on 2019-12-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchro', '0006_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
